app-banking/Models/Account.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace app_banking.Models
{
    public class Account
    {
        [Key]
        public int Id { get; set; }
        [Column(name:"account_type")]
        public string AccountType { get; set; }
        [Column(name:"account_number")]
        public string AccountNumber { get; set; } = string.Empty;
        [Column(name:"account_currency")]
        public string AccountCurrency { get; set; } = string.Empty;
        [Column(name:"user_id")]
        public int User { get; set; } = default!;
        [Column(name:"datecreated")]
        public DateTime DateCreated { get; set; }
    }
}

app-banking/Models/Enums/AccountType.cs
using System.ComponentModel.DataAnnotations;

public enum AccountType
{
    [Display(Name = "Накопительный счёт")]
    SavingAccount = 0,
    [Display(Name = "Инвестиционный счёт")]
    InvestmentAccount = 1,
    [Display(Name = "Дебетовый счёт")]
    CurrentAccount = 2
}

app-banking/Models/ErrorViewModel.cs
namespace app_banking.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

app-banking/Models/Interfaces/IAccountRepository.cs
namespace app_banking.Models.Interfaces
{
    public interface IAccountRepository
    {
        IEnumerable<Account> GetAllAccounts { get; }
        /*Account? AddAccount(Account account);
        Account UpdateAccount(Account account);
        Account DeleteAccount(Account account);
        Account? GetAccountById(int id);*/
    }
}

app-banking/Models/Interfaces/IUserRepository.cs
namespace app_banking.Models.Interfaces
{
    public interface IUserRepository
    {
        IEnumerable<User> GetAllUsers { get; }
        /*User? GetUserById(int id);*/
    }
}

app-banking/Models/Repository/ApplicationContext.cs
using app_banking.Models;
using Microsoft.EntityFrameworkCore;
using static Config;

public class ApplicationContext : DbContext
{
    public ApplicationContext(DbContextOptions<ApplicationContext> options) : base(options)
    {
    }
    public DbSet<Account> Account { get; set; }
    public DbSet<User> User { get; set; }
}

app-banking/Models/Repository/UserRepository.cs
using app_banking.Models.Interfaces;

namespace app_banking.Models.Repository;

public class UserRepository : IUserRepository
{
    private protected ApplicationContext _applicationContext;

    public UserRepository(ApplicationContext applicationContext)
    {
        _applicationContext = applicationContext;
    }
    
    public IEnumerable<User> GetAllUsers
    {
        get
        {
            return _applicationContext.User;
        }
    }

    public User? GetUserById(int id)
    {
        throw new NotImplementedException();
    }
}

app-banking/Models/User.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace app_banking.Models
{
    public class User
    {
        [Key]
        public int Id { get; set; }
        [Column(name:"user_name")]
        public string Name { get; set; } = string.Empty;
        [Column(name:"user_accountid")]
        public int AccountId { get; set; }
        [Column(name:"user_role")]
        public string Role { get; set; }
        [Column(name:"user_password")]
        public long Password { get; set; }
    }
}

app-banking/ViewModels/UserAccountsViewModel.cs
using app_banking.Models;

namespace app_banking.ViewModels
{
    public class UserAccountsViewModel
    {
        public IEnumerable<User> Users { get; }
        public IEnumerable<Account> Accounts { get; }

        public UserAccountsViewModel(IEnumerable<User> userRepository,
            IEnumerable<Account> accountRepository)
        {
            Users = userRepository;
            Accounts = accountRepository;
        }

    }
}

app-banking/Controllers/DashboardController.cs
using app_banking.Models;
using Microsoft.AspNetCore.Mvc;

namespace app_banking.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Statistics()
        {
            return View();
        }
    }
}

app-banking/Controllers/DepositController.cs
using Microsoft.AspNetCore.Mvc;

namespace app_banking.Controllers
{
    public class DepositController : Controller
    {
        public IActionResult Transfer()
        {
            return View();
        }
    }
}

app-banking/Controllers/DepositListController.cs
using app_banking.Models.Interfaces;
using app_banking.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace app_banking.Controllers
{
    public class DepositListController : Controller
    {
        private readonly IAccountRepository _accountRepository;
        private readonly IUserRepository _userRepository;

        public DepositListController(IAccountRepository accountRepository, IUserRepository userRepository)
        {
            _accountRepository = accountRepository;
            _userRepository = userRepository;
        }

        public IActionResult ShowDepositList()
        {
            UserAccountsViewModel model = new UserAccountsViewModel(_userRepository.GetAllUsers,
                _accountRepository.GetAllAccounts
            );
            return View(model);
        }
    }
}

app-banking/Controllers/HomeController.cs
using app_banking.Models;
using app_banking.Models.Interfaces;
using app_banking.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace app_banking.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IAccountRepository _accountRepository;
        private readonly IUserRepository _userRepository;

        public HomeController(IUserRepository userRepository, 
            IAccountRepository accountRepository)
        {
            _userRepository = userRepository;
            _accountRepository = accountRepository;
        }

        public IActionResult Index()
        {
            ViewBag.CurrentUser = "Maksims Racins";
            UserAccountsViewModel model = new UserAccountsViewModel(_userRepository.GetAllUsers, 
                _accountRepository.GetAllAccounts);
            return View(model);
        }

        public IActionResult UserProfile()
        {
            return View();
        }

        public IActionResult Contacts()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

app-banking/Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;

namespace app_banking.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
    }
}

app-banking/Views/Deposit/Transfer.cshtml

<div class="container">
    <div class="row">
        <div class="col">
            <form>
                <div class="form-group">
                    <label for="account">Debit account</label>
                    <input type="text" class="form-control" id="inputDebitAccount" aria-describedby="accountHelp" placeholder="Enter debit account">
                    <small id="accHelp" class="form-text text-muted"></small>
                </div>
                <div class="form-group">
                    <label for="amount">Amount</label>
                    <input type="number" class="form-control" id="inputAmount" placeholder="Amount">
                </div>
                <div class="form-group">
                    <label for="account">Credit account</label>
                    <input type="text" class="form-control" id="inputCreditAccount" placeholder="Enter credit account">
                </div>
                <button type="submit" class="btn btn-primary">Process</button>
            </form>
        </div>
        <div class="col">
        </div>
        <div class="col">
        </div>
    </div>
</div>

app-banking/Views/DepositList/ShowDepositList.cshtml
@model app_banking.ViewModels.UserAccountsViewModel

<table class="table">
    <thead>
        <tr>
            <th scope="col">Account Number</th>
            <th scope="col">Account Currency</th>
            <th scope="col">Account Type</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var acc in Model.Accounts)
        {
            <tr>
                <td>@acc.AccountNumber</td>
                <td>@acc.AccountCurrency</td>
                <td>@acc.AccountType</td>
            </tr>
        }
    </tbody>
</table>

app-banking/Views/Home/Index.cshtml
<div class="container">
    <h1>Welcome Maksims</h1>
</div>

app-banking/Views/Home/UserProfile.cshtml
<div class="container">
    <h1>Profile</h1>
</div>

app-banking/Views/Login/Login.cshtml
<form>
    <div class="form-group">
        <label for="exampleInputEmail1">Email address</label>
        <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email">
        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
    </div>
    <div class="form-group">
        <label for="exampleInputPassword1">Password</label>
        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
    </div>
    <div class="form-group form-check">
        <input type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

app-banking/Views/Shared/CssPartial.cshtml
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link href='http://fonts.googleapis.com/css?family=Oswald:400,300,700' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="~/app_banking.styles.css" asp-append-version="true" />

app-banking/Views/Shared/FooterPartial.cshtml
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - app_banking - <a asp-area="" asp-controller="Home" asp-action="">Privacy</a>
    </div>
</footer>

app-banking/Views/Shared/MetatagsPartial.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
@if (ViewBag.Title != null)
{
    <title>@Config.CompanyName</title>
}
else
{
    <title>@ViewData["Title"] - "Bank System Management"</title>
}
@if (ViewBag.Description != null)
{
    <meta name="description" content="@ViewBag.Description" />
}
@if (ViewBag.Keywords != null)
{
    <meta name="keywords" content="@ViewBag.Keywords" />
}

app-banking/Views/Shared/NavigationPartial.cshtml
<nav class="navbar navbar-fixed-top border-bottom">
    <a class="nav-link brand text-dark" asp-area="" asp-controller="Home" asp-action="Index">@Config.CompanyName</a>
    <ul class="nav justify-content-center">
        <li class="nav-item">
            <a class="nav-link active text-dark" asp-area="" asp-controller="Home" asp-action="UserProfile">User Profile</a>
        </li>

        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contacts">Contacts</a>
        </li>

        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Login">Login</a>
        </li>
    </ul>
</nav>

app-banking/Views/Shared/NavigationSidebarPartial.cshtml
<nav class="navbar navbar-fixed-left">

<ul class="nav flex-column">
    <li class="nav-item">
        <a class="nav-link text-secondary" asp-controller="Dashboard" asp-action="Statistics" >Dashboard</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-secondary" asp-controller="Deposit" asp-action="Transfer">Deposit</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-secondary" asp-controller="WithdrawList" asp-action="ShowWithdrawList">Withdraw List</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-secondary" asp-controller="DepositList" asp-action="ShowDepositList">Deposit List</a>
        </li>
</ul>
</nav>

app-banking/Views/Shared/ScriptsPartial.cshtml
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

app-banking/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
  @await Html.PartialAsync("MetatagsPartial")
  @await Html.PartialAsync("CssPartial")
</head>

<body>
<div class="container shadow-sm bg-white">
  @await Html.PartialAsync("NavigationPartial")
  
  <div class="row mb-4">
    <div class="col-2 shadow-sm bg-white">
      @await Html.PartialAsync("NavigationSidebarPartial")
    </div>
    <div class="col-10 shadow-sm p-4 bg-white">
      @RenderBody()
    </div>
  </div>
</div>

@await Html.PartialAsync("FooterPartial")
@await Html.PartialAsync("ScriptsPartial")
</body>

</html>

app-banking/Views/WithdrawList/ShowWithdrawList.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}